---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      PSR1 Classes ClassDeclaration MissingNamespace:
        enabled: false
      PSR2 Methods MethodDeclaration Underscore:
        enabled: false
  ratings:
  paths:
  - "**.php"
exclude_paths:
- vendor/**/*
