---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    checks:
      PSR1 Classes ClassDeclaration MissingNamespace:
        enabled: false
      PSR1 Methods CamelCapsMethodName NotCamelCaps:
        enabled: false
      PSR2 Methods MethodDeclaration Underscore:
        enabled: false
      Squiz Classes ValidClassName NotCamelCaps:
        enabled: false
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      UnusedLocalVariable:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- vendor/**/*
